name: Coverage

on:
  push:
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [master]
    types: [opened]
    paths-ignore:
      - '**.md'

  repository_dispatch:
    types: manual-trigger

jobs:
  run_coverage:
    if: contains(toJson(github.event.commits), '[skip ci]') == false && contains(toJson(github.event.commits), '[skip github]') == false

    runs-on: 'ubuntu-latest'

    steps:

    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r dev-requirements.txt
        python -m pip list
        echo "PYTHONPATH=home/runner/work/psautohint/build/lib" >> $GITHUB_ENV

    - name: Generate and upload Python and C coverage
      env:
        CFLAGS: '--coverage'
      run: |
        python setup.py build --build-base build --build-platlib build/lib
        python setup.py install
        python -m pytest --cov=psautohint --cov-report=xml -n auto
        bash <(curl -s https://codecov.io/bash) -y .codecov.yml
