# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2.4.1.dev50+g2735512.d20230106'
__version_tuple__ = version_tuple = (2, 4, 1, 'dev50', 'g2735512.d20230106')
